### PR TITLE
Update foundry_login.css

### PR DESCRIPTION
**Pull request by mouse0270**
Added CSS variables to set Path Locations so they are easier to access.
Added The ability to change the button colors (uses filter on hover to change button state when hovering)
Added Comments and Toggle to root to allow an easier ability to toggle world title.
Added Ability to set background image. Left as Anvil but put a comment in showing how to do it as an example.

### CODE REVIEW

**Comment by mouse0270** [comment]
Need to remove background image code as I am new to foundry and just realized you can set this up in Foundry World Settings... HAHA

**Comment by TheEpicSnowWolf** [comment]
Hi @mouse0270, thanks for the PR!

I think in general, the addition of variables is a good idea to make customization easier, however I'm not a big fan of the "world title toggle" at the moment. It's a more "dirty" way to switch between world logo/title and arguably makes the CSS much more complicated than it needs to be, while providing minimal benefits to usability over just removing one declaration and replacing another. Also, why is `background` defined twice in `#world-title h1`?.

In addition, if `--world-logo` is left as it is because a user wants to use the text title, the login page would generate at least one 404 error on every visit, which I would consider bad practice. It's better to delete that rule if a user doesn't want to use it.

Formatting would also need to be fixed, most declarations now lack proper indentation.

**Comment by TheEpicSnowWolf** [comment]
@mouse0270 Yeah, good input! To be honest, I really did not want this CSS to become too hacky, as this is kinda what bothered me with the original version that I based my code on. I have pushed a commit to your fork (wanted to create a new PR for it, but got a 404 error from GitHub?) that adds some variables for easier configuration but keeps the need to remove some code to restore the original text title.

What do you think? I'd be happy to merge this to the main branch now.

**Comment by mouse0270** [comment]
To be honest, if this was a website I was designing, there is no way I would use this hackish code. But then again I would provide a user the ability to assign things like theme color and logos... So that is more on fault with FoundryVTT. But pelase don't feel pressured to do something you don't want to, I just love CSS variables and wanted to make a few modifications using them is all.

With that said it looks great to me.

**Comment by TheEpicSnowWolf** [comment]
Don't worry, I really think the variables are a great idea to make it easier to use for people who don't know much about CSS! Thank you for your contribution, I'll merge this now and adjust the Readme and my post on Reddit accordingly. :)

**Pull request merged**
