### PR TITLE
Made it as a module

### LINKED ISSUE #7: How to use this styling without editting core css file
Hello, I just want to let you know how to use this styling without editting core css file.

You can just include this css file into your core localization module.

Here's how to make localization module.

It is pretty simple. just add one line to your module.json - "coreTranslation":true

In that way, you can apply css to your core application.

Anyways, thank you for your hard work!

### PR DESCRIPTION
**Pull request by jbblily**
Feel free to use this.

You should edit 'module.json' file line 22 after you merge this pr, if you want to download this module.

### CODE REVIEW

**Comment by kiloforce** [comment]
Yes please!  @jbblily will you be making a v10 version too?

**Comment by jbblily** [comment]
I'm afraid I can't post this as official module, because this has to be included in your Core Translation module, not as a form of independent module.

FVTT only allows one default translation module. If you are using other translation module for core, you can't use it.  

If you are non-English user, you can just add css file into your translation module.
(don't forget to add css in the manifest)

If you are an English user, just make a core translation module for random language and add this css into your module. No need to put json into it. It falls back to English if there's no translation.

**Comment by TheEpicSnowWolf** [comment]
Heya, apologies for leaving this undone for such a long time.

I've just made a couple of commits to adjust some wording/structure of the files and changed the versioning for the module into a format that resembles `[Foundry Version].[CSS/Module version within VTT version]`. As I don't think there will be many changes to the CSS/module going forward, I feel like it doesn't really warrant a 'classic' versioning system, and might be easier to keep track this way.

Are you okay with the commits? Happy to finally merge and create the release version for the module download if yes. :D

**Comment by jbblily** [comment]
Yes of course! I think this is amazing. Thank you for adjusting the module and description as well!

**Comment by TheEpicSnowWolf** [comment]
This is now merged and can confirm that it works as intended! Thanks very much again for your contribution. :)

**Pull request merged**
